// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Swiggy.Entity;

namespace Swiggy.Migrations
{
    [DbContext(typeof(SwiggyDbContext))]
    [Migration("20211106123727_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Swiggy.Entity.Customer", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Name", "Email");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Swiggy.Entity.FoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantName");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("Swiggy.Entity.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RestaurantName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RestaurantName");

                    b.HasIndex("CustomerName", "CustomerEmail");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Swiggy.Entity.Restaurant", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("Swiggy.Entity.FoodItem", b =>
                {
                    b.HasOne("Swiggy.Entity.Restaurant", null)
                        .WithMany("FoodItems")
                        .HasForeignKey("RestaurantName");
                });

            modelBuilder.Entity("Swiggy.Entity.Order", b =>
                {
                    b.HasOne("Swiggy.Entity.FoodItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("Swiggy.Entity.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantName");

                    b.HasOne("Swiggy.Entity.Customer", null)
                        .WithMany("Orders")
                        .HasForeignKey("CustomerName", "CustomerEmail");

                    b.Navigation("Item");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Swiggy.Entity.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Swiggy.Entity.Restaurant", b =>
                {
                    b.Navigation("FoodItems");
                });
#pragma warning restore 612, 618
        }
    }
}
